config/routes.rb
FantasyFootball::Application.routes.draw do
  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end
  
  resources :articles
  
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :path_names => {:sign_up => 'register'}

  resources :users, :players, :teams, :relationships, :leagues

  root :to => 'pages#home'

  get "pages/home"
  get "pages/about"
  get "pages/contact"
  get "pages/help"
  get "teams/index"
  get "teams/show"

  match '/', :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help', :to => 'pages#help'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable, :encryptable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Associations
  has_many :forums, :dependent => :destroy
  
  # Accessors
  attr_accessible :title, :state, :position, :category_id
  
  # Scopes
  default_scope :order => 'position ASC'
  
  # Validations
  validates :title,       :presence => true
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  # Associations
  has_many :topics, :dependent => :destroy
  has_many :posts, :through => :topics
  
  belongs_to :category
  
  # Accessors
  attr_accessible :title, :description, :state, :position, :category_id
  
  # Scopes
  default_scope :order => 'position ASC'
  
  # Validations
  validates :title,       :presence => true
  validates :description, :presence => true
  validates :category_id, :presence => true
end

app/models/league.rb
class League < ActiveRecord::Base
   has_many :teams

end

app/models/player.rb
class Player < ActiveRecord::Base

  has_many :relationships, :dependent => :destroy
  has_many :teams, :through => :relationships

  def add_to_team(player)
    Relationship.create!(:player_id=>player.id,
                         :team_id => current_user.team.first)

    redirect_to current_user
  end


end

app/models/post.rb
class Post < ActiveRecord::Base
  
  # Associations
  belongs_to :forum, :counter_cache => true
  belongs_to :topic, :counter_cache => true, :touch => true 
  belongs_to :user, :class_name => "User", :counter_cache => true
  
  # Accessors
  attr_accessible :body
  
  # Validations
  validates :body, :presence => true
  validates :user, :presence => true
  
  # Default Scope
  default_scope :order => 'created_at ASC'
  
  # Scope to display only the last n posts. Used for "Recent Posts" display
  scope :recent, lambda {
    |c| reorder('created_at desc').limit(c)
  }
  
  # Callbacks
  before_save :topic_locked?
  
  # Methods
  private
    def topic_locked?
      if topic.locked?
        errors.add(:base, "That topic is locked")
        false
      end
    end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :team_id, :player_id

  belongs_to :team
  belongs_to :player


  validates :player_id, :presence => true
  validates :team_id, :presence => true

end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :points, :player_ids, :relationship_id, :league_id

  belongs_to :user
  belongs_to :league

  has_many :relationships, :dependent => :destroy
  has_many :players, :through => :relationships


  validates :user_id, :presence => true
  validates :name, :presence => true, :uniqueness => true

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  # Associations
  has_many :posts, :dependent => :destroy
  belongs_to :forum, :counter_cache => true
  belongs_to :user, :class_name => "User", :counter_cache => true
  
  # Accessors
  attr_accessor :body
  attr_accessible :title, :body, :sticky, :locked
  
  # Validations
  validates :title,   :presence => true
  validates :body,    :presence => true, :on => :create
  validates :posts,   :presence => true, :allow_nil => false, :on => :update
  validates :user,    :presence => true
  
  # Scopes
  default_scope :order => 'sticky DESC, updated_at DESC'
  
  # Callbacks
  after_create :create_initial_post
  
  # Methods
  def hit!
    self.class.increment_counter :hits, id
  end
  
  private
    def create_initial_post
      self.posts.build(:body => self.body).tap do |post|
        post.forum = self.forum
        post.user = self.user
        post.save
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :about_me, :location, :team, :forem_admin

  has_many :teams, :dependent => :destroy
  has_many :topics, :dependent => :destroy
  has_many :posts, :dependent => :destroy

  validates :about_me, :length => { :maximum => 500 }
  validates :email, :presence => true
  validates :username, :presence => true

  def admin?
    true if self.username == 'admin'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title="Home"
    @articles = Article.last(5)
  end

  def contact
    @title="Contact"
  end

  def about
    @title="About"
  end

  def help
    @title="Help"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Fantasy Football"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def sortable(column, title=nil)
    title ||=column.titleize
    direction = column == sort_column && sort_direction =="asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end

  def markdown(text)
   markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
   markdown.render(text).html_safe
  end



    @my_blockquote = {
    'Quote' => [
      /\[quote\](.*?)\[\/quote\1?\]/mi,
      '<blockquote>\3</blockquote>',
      'Quote with citation',
      '[quote=mike]please quote me[/quote]',
      :quote
    ],
  }
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/team_helper.rb
module TeamHelper
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.username),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

  def deny_access
    redirect_to signin_path, :alert => "Please sign in to access this page."
  end

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <%= link_to "About", main_app.about_path %> |
    <%= link_to "Contact", main_app.contact_path %> |
    <%= link_to "Help", main_app.help_path %> |
  </nav>
</footer>

app/views/layouts/_leftnav.html.erb

  <nav class="round">
    <ul>
        <li> <%= if !current_admin_user && signed_in? then "Welcome #{current_user.username}" end %></li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Forums", forums_path %></li>
        <li><%= link_to "Articles", main_app.articles_path %></li>
        <li><%= link_to "Players", main_app.players_path %></li>
       <% if !current_admin_user && signed_in? %>
        <li><%= link_to "Users", main_app.users_path %></li>
        <li><%=link_to "Profile", main_app.user_path(current_user) %></li>
        <li><%= link_to "My Teams", main_app.teams_path %></li>
        <li><%= link_to "New Team", main_app.new_team_path %></li>
        <li><%= link_to "Settings", main_app.edit_user_registration_path %></li>
        <li><%= link_to "Sign out", main_app.destroy_user_session_path, :method => :delete %>
      <% else %>
           <%= link_to "Sign up", main_app.new_user_registration_path %> or <%= link_to "sign in", main_app.new_user_session_path %>
      <% end %>
    </ul>
  </nav>

app/views/layouts/_rightnav.html.erb
<a href="https://twitter.com/PortlaoiseGAA" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @PortlaoiseGAA</a><br /><br />
<div class="fb-like-box" data-href="https://www.facebook.com/pages/Portlaoise-GAA-Club/108542145841275" data-width="auto" data-show-faces="true" data-stream="true" data-header="true"></div><br />

<script>    !function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = "//platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); } } (document, "script", "twitter-wjs");</script><br /><br />
<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
    new TWTR.Widget({
        version: 2,
        type: 'profile',
        rpp: 4,
        interval: 30000,
        width: 300,
        height: 300,
        theme: {
            shell: {
                background: '#333333',
                color: '#ffffff'
            },
            tweets: {
                background: '#000000',
                color: '#ffffff',
                links: '#4aed05'
            }
        },
        features: {
            scrollbar: false,
            loop: false,
            live: false,
            behavior: 'all'
        }
    }).render().setUser('PortlaoiseGAA').start();
</script>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag "forum-monster" %>
<%= stylesheet_link_tag 'main', :media => 'screen' %>
<link rel="stylesheet" type="text/css" href="test.css" />



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= javascript_include_tag :application %>
    <%= javascript_include_tag :defaults %>

    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <script>        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        } (document, 'script', 'facebook-jssdk'));</script>
  </head>
  <body>
    <div id="wrapper">
        <div id="header">

        </div>
         <hr>
        <div id="leftnav">
          <%= render 'layouts/leftnav' %>
        </div>

        <div id="content">
          <% if !notice.nil? %>
            <p class="notice"><%= notice %></p><% end %>
           <% if !alert.nil? %>
            <p class="alert"><%= alert %></p><% end %>

            <%= yield %>
        </div>

        <div id="footer">
          <hr>
          <%= render 'layouts/footer' %>
        </div>
    </div>
  </body>
</html>

app/views/shared/_articles.html.erb
<% if !@articles.nil? then %>
<% @articles.reverse.each do |article| %>
    <h2><%= link_to "#{article.headline}", article_path(article) %></h2> <br />
    by <strong><%= article.author %></strong> posted <%= time_ago_in_words(article.created_at) %> ago<br />
    <em><%= simple_format(article.description) %></em><br />
    <%= simple_format("#{article.content.first(800)}...") %>
    <%= link_to 'Read More', article_path(article) %><br />
<hr>

<br />
<br />
<% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_team_form.html.erb
<%= semantic_form_for @team do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.input :players, :collection => Player.all, :as => :select, :include_blank => "Players" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.username %>
    </span>
    <span class="teams">
      <%= pluralize(current_user.teams.count, "team") %>
    </span>
  </a>
</div>